### ISSUE TITLE
TypeError: Cannot set property 

### ISSUE THREAD

**Issue by Piotr020798** [andrewda/hltv-scorebot#8]
/var/www/test/node_modules/hltv-scorebot/Scorebot.js:285
        this.players[player.name] = {
                                  ^

TypeError: Cannot set property 'Rickeh intel' of undefined
    at /var/www/test/node_modules/hltv-scorebot/Scorebot.js:285:35
    at Array.forEach (native)
    at updatePlayers (/var/www/test/node_modules/hltv-scorebot/Scorebot.js:284:7)
    at Scorebot.onScoreboard (/var/www/test/node_modules/hltv-scorebot/Scorebot.js:170:5)
    at Socket.Emitter.emit (/var/www/test/node_modules/component-emitter/index.js:134:20)
    at Socket.onevent (/var/www/test/node_modules/socket.io-client/lib/socket.js:254:10)
    at Socket.onpacket (/var/www/test/node_modules/socket.io-client/lib/socket.js:212:12)
    at Manager.<anonymous> (/var/www/test/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/var/www/test/node_modules/component-emitter/index.js:134:20)
    at Manager.ondecoded (/var/www/test/node_modules/socket.io-client/lib/manager.js:301:8)

**Comment by andrewda** [comment]
I can't seem to duplicate this error. What's the code you're using?

**Comment by andrewda** [comment]
https://github.com/andrewda/hltv-scorebot/commit/3210597315a9845ff9db18d0061b8aa1ce9eae85 should fix it
